export const commonMajorsInBD = [
  "Accounting",
  "Anthropology",
  "Architecture",
  "Bangla",
  "Biochemistry",
  "Biotechnology",
  "Business Administration (BBA)",
  "Chemistry",
  "Civil Engineering",
  "Computer Science and Engineering (CSE)",
  "Data Science",
  "Economics",
  "Electrical and Electronic Engineering (EEE)",
  "English",
  "Environmental Science",
  "Finance",
  "Graphic Design",
  "History",
  "Human Resource Management (HRM)",
  "Information Technology (IT)",
  "International Relations",
  "Islamic Studies",
  "Journalism and Media Studies",
  "Law (LLB)",
  "Management",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Microbiology",
  "Nursing",
  "Pharmacy",
  "Physics",
  "Political Science",
  "Public Administration",
  "Public Health",
  "Sociology",
  "Software Engineering",
  "Statistics",
  "Supply Chain Management",
  "Textile Engineering",
  "Tourism and Hospitality Management",
  "Other"
];
