export const universitiesInBD = [
  "Ahsanullah University of Science and Technology (AUST)",
  "American International University-Bangladesh (AIUB)",
  "Anwer Khan Modern University",
  "ASA University Bangladesh",
  "Asian University for Women (AUW)",
  "Asian University of Bangladesh",
  "Atish Dipankar University of Science and Technology",
  "Bangabandhu Sheikh Mujib Medical University (BSMMU)",
  "Bangabandhu Sheikh Mujibur Rahman Agricultural University",
  "Bangabandhu Sheikh Mujibur Rahman Aviation and Aerospace University",
  "Bangabandhu Sheikh Mujibur Rahman Digital University",
  "Bangabandhu Sheikh Mujibur Rahman Maritime University",
  "Bangabandhu Sheikh Mujibur Rahman Science and Technology University",
  "Bangamata Sheikh Fojilatunnesa Mujib Science and Technology University",
  "Bangladesh Agricultural University (BAU)",
  "Bangladesh Army International University of Science and Technology",
  "Bangladesh Army University of Engineering & Technology",
  "Bangladesh Army University of Science and Technology",
  "Bangladesh Islami University",
  "Bangladesh Open University",
  "Bangladesh University",
  "Bangladesh University of Business and Technology (BUBT)",
  "Bangladesh University of Engineering and Technology (BUET)",
  "Bangladesh University of Professionals (BUP)",
  "Bangladesh University of Textiles (BUTEX)",
  "Barisal University",
  "Begum Rokeya University, Rangpur",
  "BGMEA University of Fashion and Technology (BUFT)",
  "BRAC University",
  "Britannia University",
  "Canadian University of Bangladesh",
  "Central Women's University",
  "Chandpur Science and Technology University",
  "Chittagong Independent University",
  "Chittagong Medical University",
  "Chittagong University of Engineering and Technology (CUET)",
  "City University",
  "Comilla University",
  "Cox's Bazar International University",
  "Daffodil International University (DIU)",
  "Darul Ihsan University",
  "Dhaka International University (DIU)",
  "Dhaka Medical College",
  "Dhaka University",
  "Dhaka University of Engineering & Technology (DUET)",
  "East Delta University",
  "East West University (EWU)",
  "Eastern University",
  "European University of Bangladesh",
  "Exim Bank Agricultural University Bangladesh",
  "Fareast International University",
  "Feni University",
  "First Capital University of Bangladesh",
  "Global University Bangladesh",
  "Gono Bishwabidyalay",
  "Green University of Bangladesh",
  "Habiganj Agricultural University",
  "Hajee Mohammad Danesh Science & Technology University (HSTU)",
  "Hamdard University Bangladesh",
  "IBAIS University",
  "Independent University, Bangladesh (IUB)",
  "International Islamic University Chittagong (IIUC)",
  "International Standard University",
  "International University of Business Agriculture and Technology (IUBAT)",
  "Ishakha International University",
  "Islamic Arabic University",
  "Islamic University, Bangladesh",
  "Islamic University of Technology (IUT)",
  "Jagannath University (JnU)",
  "Jahangirnagar University (JU)",
  "Jatiya Kabi Kazi Nazrul Islam University",
  "Jessore University of Science and Technology (JUST)",
  "Khwaja Yunus Ali University",
  "Khulna Agricultural University",
  "Khulna University",
  "Khulna University of Engineering & Technology (KUET)",
  "Kurigram Agricultural University",
  "Leading University",
  "Manarat International University",
  "Mawlana Bhashani Science and Technology University (MBSTU)",
  "Metropolitan University",
  "Midlands University",
  "National University, Bangladesh",
  "Noakhali Science and Technology University (NSTU)",
  "North Bengal International University",
  "North South University (NSU)",
  "North Western University",
  "Northern University Bangladesh",
  "Notre Dame University Bangladesh",
  "Pabna University of Science and Technology",
  "Patuakhali Science and Technology University",
  "Port City International University",
  "Premier University",
  "Presidency University",
  "Prime University",
  "Primeasia University",
  "Pundra University of Science and Technology",
  "Queens University",
  "Rabindra University, Bangladesh",
  "Rajshahi Medical University",
  "Rajshahi Science and Technology University",
  "Rajshahi University",
  "Rajshahi University of Engineering & Technology (RUET)",
  "Rangamati Science and Technology University",
  "Royal University of Dhaka",
  "Shahjalal University of Science and Technology (SUST)",
  "Shanto-Mariam University of Creative Technology",
  "Sheikh Fazilatunnesa Mujib University",
  "Sheikh Hasina University",
  "Sher-e-Bangla Agricultural University",
  "Sonargaon University",
  "Southeast University",
  "Southern University Bangladesh",
  "Stamford University Bangladesh",
  "State University of Bangladesh",
  "Sylhet Agricultural University",
  "Sylhet International University",
  "Sylhet Medical University",
  "Times University Bangladesh",
  "United International University (UIU)",
  "University of Asia Pacific (UAP)",
  "University of Barishal",
  "University of Brahmanbaria",
  "University of Chittagong",
  "University of Creative Technology Chittagong",
  "University of Development Alternative",
  "University of Global Village",
  "University of Information Technology and Sciences (UITS)",
  "University of Liberal Arts Bangladesh (ULAB)",
  "University of Scholars",
  "University of Science & Technology Chittagong",
  "University of South Asia",
  "Uttara University",
  "Varendra University",
  "Victoria University of Bangladesh",
  "World University of Bangladesh",
  "Z.H. Sikder University of Science and Technology",
  "Other"
];
